[package]
name = "youtube_downloader"
version = "0.1.0"
edition = "2021"
authors = ["malakai gunderson <discord: !kaifungaming#2947>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube ="0.6.0"
futures = "0.3.25"
tokio = {version = "1.21.2",  features = ["full"] }
ytextract = "0.11.0"

